CREATE TABLE `clinic` 
(
  `id` INT NOT NULL AUTO_INCREMENT ,
  `name` VARCHAR(100) DEFAULT NULL ,
  `address` VARCHAR(500) DEFAULT NULL,
  `alias` VARCHAR(50) DEFAULT NULL,
  `color` VARCHAR(100) DEFAULT '#FFFFF',
  `bitrix_id` VARCHAR(100) DEFAULT NULL,
  `update` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `cdate` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
  ) 
ENGINE = InnoDB;