CREATE TABLE `contact`
(
    `id` INT NOT NULL AUTO_INCREMENT ,
    `max_user_id` INT DEFAULT NULL,
    `max_chat_id` INT DEFAULT NULL,
    `step_authorization` INT(1) DEFAULT NULL,
    `phone` VARCHAR(25) DEFAULT NULL,
    `name` VARCHAR(300) DEFAULT NULL,
    `update` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `cdate` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
)
ENGINE = InnoDB;