CREATE TABLE `edna` 
(
  `id` INT NOT NULL AUTO_INCREMENT ,
  `cascade_id` VARCHAR(50) NOT NULL,
  `api` VARCHAR(1000) ,
  `is_actual` TINYINT(1) DEFAULT 1,
  `update` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `cdate` DATETIME DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (`id`)
)