CREATE TABLE `group_sample`
(
    `id` INT NOT NULL AUTO_INCREMENT ,
    `name` VARCHAR(200),
    `update` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `cdate` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
)
ENGINE = InnoDB