CREATE TABLE `history` 
(
  `id` INT NOT NULL AUTO_INCREMENT ,
  `entity` VARCHAR(20) DEFAULT NULL,
  `entity_id` INT,
  `subentity_id` INT DEFAULT NULL,
  `type` INT(1) DEFAULT '1',
  `user_id` INT DEFAULT '0',
  `field` VARCHAR(40),
  `new_change` VARCHAR(300) DEFAULT NULL,
  `old_change` VARCHAR(300) DEFAULT NULL,
  `update` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `cdate` DATETIME DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (`id`)
  )  
ENGINE = InnoDB;