CREATE TABLE `taxpayer_list`
(
    `id` INT NOT NULL AUTO_INCREMENT ,
    `type_id` INT DEFAULT NULL,
    `name` VARCHAR(100) DEFAULT NULL,
    `update` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `cdate` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
)
ENGINE = InnoDB;