ALTER TABLE `sample_messange_wa` ADD `group_type` INT NULL DEFAULT NULL AFTER `text`;
ALTER TABLE `sample_messange_wa` ADD `name` VARCHAR(200) NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `header` ADD `type` VARCHAR(50) NULL DEFAULT NULL AFTER `text`;
ALTER TABLE `buttons` ADD `is_url_postfix` TINYINT(1) NOT NULL DEFAULT '0' AFTER `url_postfix`;
ALTER TABLE `variable` ADD `format` VARCHAR(100) NULL DEFAULT NULL AFTER `type`;
ALTER TABLE `users` ADD `temporary_password` TINYINT(1) NOT NULL DEFAULT '0' AFTER `type`;
ALTER TABLE `nalog` ADD `taxpayer_type_id` INT DEFAULT NULL;
ALTER TABLE `nalog` ADD `taxpayer_fio` VARCHAR(300) DEFAULT NULL;
ALTER TABLE `nalog_clinic_files` ADD `relat` VARCHAR(500) NULL DEFAULT NULL AFTER `url_file`;
ALTER TABLE `nalog_clinic_files` ADD `origin` VARCHAR(100) NULL DEFAULT NULL AFTER `url_file`;
ALTER TABLE `nalog_clinic_files` ADD `name` VARCHAR(100) NULL DEFAULT NULL AFTER `url_file`;
ALTER TABLE `nalog_clinic_files` ADD `path` VARCHAR(100) NULL DEFAULT NULL AFTER `url_file`;
ALTER TABLE `nalog` ADD `hash` VARCHAR(100) DEFAULT NULL;
ALTER TABLE `sample_messange_wa` CHANGE `check number` `check_number` INT NULL DEFAULT '0';
ALTER TABLE `nalog_clinic` ADD `license_id` INT NULL DEFAULT NULL AFTER `clinic_id`;
ALTER TABLE `nalog_clinic` ADD `is_place` TINYINT(1) NOT NULL DEFAULT '0' AFTER `user_id`;
ALTER TABLE `nalog_clinic` ADD `no_doc` TINYINT(1) NOT NULL DEFAULT '0' AFTER `is_place`;
ALTER TABLE `nalog` ADD `taxpayer_date_birth` DATE NULL DEFAULT NULL AFTER `taxpayer_fio`;
ALTER TABLE `contact` ADD `code` INT(6) NULL DEFAULT NULL AFTER `cdate`;